### ISSUE TITLE
how to sue shell-logger.sh

### ISSUE THREAD

**Issue by a4200** [rcmdnk/shell-logger#1]
Hi, I copied this file in /tmp location .
how to use this script to see the output ?

**Comment by rcmdnk** [comment]
Please refer [README](https://github.com/rcmdnk/shell-logger/blob/master/README.md).

If you copied **shell-logger.sh** at **/tmp/shell-logger.sh**,
do:

    $ source /tmp/shell-logger.sh
    $ err This is error!
    $ warn warning
    $ debug debug test

Then you will see a red error, yellow warning, and no debug messages.

Or you can make a script like

```bash
#!/usr/bin/env bash
source /tmp/shell-logger.sh

err This is error!
warn warning
debug debug test
```
